posthtml-webp
posthtml/posthtml-plugin-boilerplate pull request #4
Opened 2016-10-02 12:58 UTC by seokirill

New plugin for poshtml called "posthtml-webp".

Add webp supporting in html.

2016-10-02 16:10 UTC, michael-ciniawsky commented
Cool 👍  😛 . But why are you sending are PR to the boilerplate repo ? If you want the add your plugin to e.g the [Plugins List](https://github.com/posthtml/posthtml#img--svg) please do the flowing instead:

- fork posthtml/posthtml
- Modify README.md
  - add your plugin to the IMG && SVG section table

  ```markdown
  |[posthtml-webp][webp]|[![npm][webp-badge]][webp-npm]|Add WebP support for images|
  ```
   - add the plugin links under the table

  ```markdown
  [webp]: https://github.com/posthtml/posthtml-webp
  [webp-badge]: https://img.shields.io/npm/v/posthtml-webp.svg
  [webp-npm]: https://npmjs.com/package/posthtml-webp
  ```
- send PR to posthtml/posthtml

2016-10-02 16:33 UTC, seokirill commented
Im so sorry, but my english lewel is not so high.  Read a lot of text is to hard for me. My native language is Russian.

Thanks for instructions. (:

2016-10-02 16:53 UTC, michael-ciniawsky requested changes
:+1 Again very cool, if you find the time, please add one or two test :), when help needed feel free to ask

2016-10-02 16:53 UTC, michael-ciniawsky commented on lib/index.js
> +  return function posthtml_webp (tree) {
posthtml_webp -> posthtmlWebP

The PLUGIN_NAME is misleading here, since it's more common to use camelCase as naming convention for plugins :)

2016-10-02 16:53 UTC, michael-ciniawsky commented on lib/index.js
> +    tree.match({ tag: 'img' }, function (imgNode) {
I would recommend to either use the tagName only ``` function (img) {...}``` or use the generic name ```function (node) {...}```. But this comment is absolutely negletable :)

2016-10-02 16:53 UTC, michael-ciniawsky commented on README.md
> -See [PostHTML Guidelines](https://github.com/posthtml/posthtml/tree/master/docs) and [contribution guide](CONTRIBUTING.md).
```
 ### CONTRIBUTING -> ## CONTRIBUTING

[contribution guide] -> [CONTRIBUTING]
```

2016-10-02 16:53 UTC, michael-ciniawsky commented on README.md
>  ### License [MIT](LICENSE)
```
## LICENSE

[MIT](LICENSE)
```

or skip it, since gihub is displaying the LICENSE anyways now ;)

2016-10-02 16:53 UTC, michael-ciniawsky commented on lib/index.js
> +function getPicture(imgNode) {
If you are interested in making this a more generic plugin (e.g posthtml-img, posthtml-images) for  ``` <img /> ``` tags in general, adding responsiveness, srcset  for different viewports, resolution,  (e.g images.png@2X etc.) + support for other images formats in the future maybe separate in ```lib/webP.js, lib/2X.js, ....```

2016-10-02 16:53 UTC, michael-ciniawsky commented on README.md
>  posthtml()
```js
import { readFileSync } from 'fs'
import posthtml from 'posthtml'
import webP from 'posthtml-webp'

const html = readFileSync('./index.html', 'utf8')

posthtml([ webP() ])
  .process(html)
  .then(({ html }) => console.log(html)) 
```

2016-10-02 16:54 UTC, michael-ciniawsky commented
kk @voischev @GitScrum  can one of you please assist with translation please ? :)

2016-10-02 20:11 UTC, GitScrum commented
@michael-ciniawsky not problem ))
@seokirill Михаил спрашивает заме сюда pull request сделал ?
Создай репозиторий posthtml-webp и в последсвии можешь передать его в posthtml организацию. Либо оставить у себя и внести изменения в readme posthtml.

2016-10-02 20:39 UTC, michael-ciniawsky commented
@GitScrum  :+1 Thx

2016-10-03 06:09 UTC, seokirill commented
@GitScrum Так я создал у себя такой репозиторий:
https://github.com/seokirill/posthtml-webp
Пытался разобраться, как добавить его в список плагинов. По мне так это штука очень нужная. Пущай люди пользуются.

2016-10-03 07:08 UTC, seokirill commented on lib/index.js
> +    tree.match({ tag: 'img' }, function (imgNode) {
- [x] Do this
I saw it in this:
https://github.com/posthtml/posthtml-img-autosize/blob/master/lib/imgAutosize.es6
(:

2016-10-03 07:10 UTC, seokirill commented on lib/index.js
> +function getPicture(imgNode) {
- [] Do this

I will code it later.

2016-10-03 07:24 UTC, seokirill commented on lib/index.js
> +  return function posthtml_webp (tree) {
- [x] Do this

2016-10-03 07:25 UTC, seokirill commented on README.md
>  posthtml()
- [x] Do this

2016-10-03 07:28 UTC, seokirill commented on README.md
> -See [PostHTML Guidelines](https://github.com/posthtml/posthtml/tree/master/docs) and [contribution guide](CONTRIBUTING.md).
https://github.com/posthtml/posthtml-plugin-boilerplate/edit/master/README.md

2016-10-03 07:29 UTC, seokirill commented on README.md
>  ### License [MIT](LICENSE)
- [x] Do this

2016-10-03 11:12 UTC, GitScrum commented
@seokirill Несомненно нужная.
Есть два варианта добавить:

1. Вариант
  - [ ] Делаете форк posthtml
  -  [ ] Добавляете свой пакет в список  
  _я могу сделать это за вас с вашего согласия_

2. Передаете свой репозиторий в posthtml организацию
  - Заходитк в настройки `settings` репозитория `posthtml-webp`
  - Нажимаете  `transfer` в графе `Transfer ownership`
  - Указываете имя репозитория который хотите передать в вашем случае `posthtml-webp` в поле `Type the name of the repository to confirm`
  - Указываете ползователя/организацию в поле `New owner’s GitHub username or organization name` для вас это `posthtml`  
_В этом случае ваш репозиторий будет находиться в `posthtml` организации._

Выбор за вами )

2016-10-03 12:06 UTC, voischev commented
Это закрываем?)

2016-10-03 12:19 UTC, seokirill commented
Да, запуллреквестил, осталось ждать ответа :/

2016-10-03 13:05 UTC, closed without merging